#profile
spring:
  profiles:
    active: test

  # freemarker
  freemarker:
    cache: false
    charset: UTF-8
    suffix: .html
    request-context-attribute: request
    template-loader-path: classpath:/templates


server:
  port: 8019
  servlet:
    context-path: /pmp

  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    # 通用配置
    additional-tld-skip-patterns: jaxb-api.jar,jaxb-core.jar
